### ISSUE TITLE
Compare fflate with lzwcompress

### ISSUE THREAD

**Issue by andinus** [noledgebin/frontend#3]

**Comment by Pauloper1** [comment]
**Fflate**

- For randomly generated strings , Average time is considered of n number of tests ran I.e. each test would produce new generated random string and this string is compressed and the time taken to compressed is calculated.
- The tests for 100 randomly generated strings of length 100 or 1000 didn’t make sense since the Average time taken was less than the time taken for individual tests 

- Also it seems for fflate takes more time to compress string for first few string and then subsequently time taken drops 


Eg1 
![1](https://user-images.githubusercontent.com/88343134/139532555-54db35b6-daca-4a65-a277-87fb320c59d8.png)
![2](https://user-images.githubusercontent.com/88343134/139532562-5f9eec67-474c-4dc0-b14c-8767eb8c22ec.png)
Eg2

![3](https://user-images.githubusercontent.com/88343134/139532569-69f243de-9d17-4662-9a8e-72ebd4b0709f.png)
![5](https://user-images.githubusercontent.com/88343134/139532572-cf0974e8-56a9-446a-8bc2-86721aff1543.png)

**For LWZ compress**

- Compared to fflate , LWZ has higher Average time taken
- Similar to fflate , the LWZ takes more time to compress string for first few string and then subsequently time taken drops 

For now, fflate leads

**Comment by Pauloper1** [comment]
Also hauffmanCompression is behaving differently for randomly generated strings but seems to work for hard-coded string

**Comment by andinus** [comment]
Can you link to the test script as well? Also, testing compression algorithms on randomly generated strings just gives us worst case result.

**Comment by andinus** [comment]
Okay, so the consensus is to use `fflate`.
